Add semver installation to CI job (#56)
* Add semver installation to CI job

* Add condition to fail in case semver is missing

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -113,6 +113,9 @@ jobs:
       - name: Build packages
         run: pnpm build
 
+      - name: Install semver
+        run: npm install -g semver
+
       - name: Check if GitHub repo package version is latest
         env:
           NODE_AUTH_TOKEN: ${{secrets.npm_token}}
@@ -130,6 +133,10 @@ jobs:
 
           # Compare the repo and NPMjs.com package versions.
           IS_GREATER=$(semver --range ">$PUBLISHED_VERSION" $REPO_VERSION || true)
+          if [ $? -ne 0 ]; then
+            echo "semver command failed"
+            exit 1
+          fi
           if [ -n "$IS_GREATER" ] ; then
             echo "@tbdex/${{ matrix.package }}@$REPO_VERSION is latest"
             echo "IS_LATEST=true" >> $GITHUB_ENV
